apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: vms
  namespace: openshift-gitops
spec:
  generators:
  - list:
      elements:
      - namespace: blue
      - namespace: green
      - namespace: black
      - namespace: white
      - namespace: tenant-a
      - namespace: tenant-b
      - namespace: tenant-x
      - namespace: tenant-y
  goTemplate: true
  template:
    metadata:
      name: '{{.namespace}}-vm'
      namespace: openshift-gitops
    spec:
      destination:
        namespace: '{{.namespace}}'
        server: https://api.cluster1.ocp.local:6443
      project: default
      source:
        path: kustomize/vms
        repoURL: https://github.com/hpe-ii-kaito/virt-gitops.git
        targetRevision: HEAD
