apiVersion: k8s.ovn.org/v1
kind: ClusterUserDefinedNetwork
metadata:
  name: blue-green-l2
spec:
  namespaceSelector: 
    matchExpressions: 
    - key: kubernetes.io/metadata.name 
      operator: In 
      values:
      - green
      - blue
  network: 
    topology: Layer2 
    layer2: 
      role: Primary 
      subnets: 
        - 10.200.0.0/16
---
apiVersion: k8s.ovn.org/v1
kind: ClusterUserDefinedNetwork
metadata:
  name: white-black-l3
spec:
  namespaceSelector: 
    matchExpressions: 
    - key: kubernetes.io/metadata.name 
      operator: In 
      values:
      - white
      - black
  network: 
    topology: Layer3 
    layer3: 
      role: Primary 
      subnets: 
        - cidr: 10.100.0.0/16
          hostSubnet: 24

