apiVersion: kubevirt.io/v1
kind: VirtualMachine
metadata:
  name: fedora
spec:
  runStrategy: Always
  template:
    spec:
      domain:
        cpu:
          cores: 4
          sockets: 1
          threads: 2
        memory:
          guest: 4096M
        devices:
          rng: {}
          interfaces:
            - name: default
              masquerade: {}
            - name: net-0
              bridge: {}
              model: virtio
      volumes:
      - dataVolume:
          name: ds-fedora
        name: ds-fedora
      - cloudInitNoCloud:
          userData: |-
            #cloud-config
            user: user
            password: password
            chpasswd: { expire: False }
          networkData: |
            ethernets:
              enp2s0:
                dhcp4: false
                addresses:
                - 192.168.31.10/24
                nameservers:
                  addresses:
                  - 192.168.31.122
        name: cloudinitdisk
      networks:
      - name: default
        pod: {}
      - multus:
          networkName: dev-vlan31
        name: net-0
