apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization


namePrefix: dev-

patches:
- patch: |
    - op: replace
      path: /spec/template/spec/domain/memory/guest
      value: 4096M
  target:
    kind: VirtualMachine

resources:
- ../base
