apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namePrefix: dev-

patches:
- path: fedora-patch.yaml
- path: rhel-patch.yaml
- path: nad-vlan31-patch.yaml
  target:
    kind: NetworkAttachmentDefinition
    name: vlan31
- path: nad-vlan32-patch.yaml
  target:
    kind: NetworkAttachmentDefinition
    name: vlan32
- path: nad-vlan33-patch.yaml
  target:
    kind: NetworkAttachmentDefinition
    name: vlan33
- target:
    kind: MultiNetworkPolicy
  patch: |-
    - op: add
      path: /metadata/annotations/k8s.v1.cni.cncf.io~1policy-for
      value: hpe-ii/dev-vlan31
- target:
    kind: MultiNetworkPolicy
    name: allow-external
  patch: |-
    - op: replace
      path: /spec/podSelector/matchLabels/vm.kubevirt.io~1name
      value: dev-fedora

resources:
- ../base
