apiVersion: kubevirt.io/v1
kind: VirtualMachine
metadata:
  name: fedora
spec:
  runStrategy: Always
  dataVolumeTemplates:
  - metadata:
      name: ds-fedora
    spec:
      sourceRef:
        kind: DataSource
        name: fedora
        namespace: openshift-virtualization-os-images
      storage:
        resources: {}
  template:
    spec:
      terminationGracePeriodSeconds: 180
      accessCredentials:
      - sshPublicKey:
          propagationMethod:
            noCloud: {}
          source:
            secret:
              secretName: bastion-key
      domain:
        memory:
          guest: 1024M
        devices:
          rng: {}
          interfaces:
            - name: default
              masquerade: {}
            - name: net-0
              bridge: {}
      volumes:
      - dataVolume:
          name: ds-fedora
        name: ds-fedora
      - cloudInitNoCloud:
          userData: |-
            #cloud-config
            password: password
            chpasswd: { expire: False }
          networkData: |
            version: 2
            ethernets:
              enp2s0:
                dhcp4: false
                addresses:
                - 192.168.31.11/24
                nameservers:
                  addresses:
                  - 192.168.31.122
        name: cloudinitdisk
      networks:
      - name: default
        pod: {}
      - multus:
          networkName: hpe-ii/vlan31
        name: net-0
